ci(fallback): don't fall back to local Rust build if precompiled asset not available

diff --git a/install-bls-signatures b/install-bls-signatures
--- a/install-bls-signatures
+++ b/install-bls-signatures
@@ -17,10 +17,15 @@ if download_release_tarball tarball_path "${subm_dir}"; then
     cp "${tmp_dir}/lib/libbls_signatures.a" .
     cp "${tmp_dir}/lib/pkgconfig/libbls_signatures.pc" .
 else
-    (>&2 echo "failed to find or obtain precompiled assets for ${subm_dir}, falling back to local build")
-    build_from_source "${subm_dir}"
+    if [ $CI = "true" ]; then
+        (>&2 echo "failed to find or obtain precompiled assets for ${subm_dir}, falling back to local build")
+        build_from_source "${subm_dir}"
 
-    find "${subm_dir}" -type f -name libbls_signatures.h -exec cp -- "{}" . \;
-    find "${subm_dir}" -type f -name libbls_signatures_ffi.a -exec cp -- "{}" libbls_signatures.a \;
-    find "${subm_dir}" -type f -name libbls_signatures.pc -exec cp -- "{}" . \;
+        find "${subm_dir}" -type f -name libbls_signatures.h -exec cp -- "{}" . \;
+        find "${subm_dir}" -type f -name libbls_signatures_ffi.a -exec cp -- "{}" libbls_signatures.a \;
+        find "${subm_dir}" -type f -name libbls_signatures.pc -exec cp -- "{}" . \;
+    else
+        (>&2 echo "build failed: could not obtain precompiled assets for ${subm_dir} - contact @laser or @dignifiedquire")
+        exit 1
+    fi
 fi
